### ISSUE TITLE
History tab appears if not assigned to the specific template but to another template

### ISSUE THREAD

**Issue by kixe** [teppokoivula/VersionControl#12]
If VersionControl is added to **one single template**, the tab will appear in **every page** UI.

The hook in **ProcessPageEdit::getTabs()** added by **init()** is assigned if the property (array) $enabled_templates is not empty. This check is a bit lazy.

**Solution:**
Move the hook inside hook function **buildFormHistory()** _Line 971_ after checking data:
```
if (!$data) return;
$this->addHookAfter('ProcessPageEdit::getTabs', $this, 'addTabHistory');
```

**Comment by teppokoivula** [comment]
Thanks, this should be fixed now :)
