### ISSUE TITLE
Text in the compare container overflows

### ISSUE THREAD

**Issue by fbg13** [teppokoivula/VersionControl#18]
The text in the compare container does not wrap to new lines since the parent _td_ has **white-space** set to **nowrap**;.

ProcessWire 3.0.91 

![ws](https://user-images.githubusercontent.com/6839895/36071943-a6ec4bae-0f1f-11e8-9936-eb03cf3ed1c7.gif)

**Comment by teppokoivula** [comment]
Thanks! This should be fixed in the latest version :)
