### ISSUE TITLE
Small CSS issue with new AdminThemeUikit

### ISSUE THREAD

**Issue by fijha** [teppokoivula/VersionControl#21]
Add ` width: auto !important;` to `.field-revisions` class.

```
VersionControl.css (line 39)

.field-revisions {
    width: auto !important;
    padding: 36px 0 0 0 !important;
    overflow: visible !important;
    position: absolute;
    margin-top: -28px;
    display: none;
    z-index: 99;
    right: 10px;
}
```

**Comment by sjardim** [comment]
I also had to add position: relative to the parent li tag, otherwise, the revisions div will display far from its field on large resolutions. Also removed bullets on UL, so, all the css looks like:
`.Inputfield {
    position: relative;
}

.field-revisions {
   ...
    width: auto !important;
}

.field-revisions ul {
   ...
    list-style: none
}`

**Comment by teppokoivula** [comment]
Thanks – these have been implemented.
