### ISSUE TITLE
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x92\x99

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#24]
Hi @teppokoivula - I have a textarea field that user are inserting emojis into and because VersionControl doesn't set up its DB tables and fields as `utf8mb4`, I get the error mentioned in the title.

I manually adjusted the tables and relevant fields and it's all good now, but it would be good if the module handled this by default.

Thanks,
Adrian

**Comment by teppokoivula** [comment]
This is fixed in the dev branch.

The approach is same as with the core itself: install time tables are created using the engine and charset defined in config, but if one changes that setting afterwards, related database changes need to be done manually.
