### ISSUE TITLE
Parse error on dev branch

### ISSUE THREAD

**Issue by Toutouwai** [teppokoivula/VersionControl#27]
[Trailing comma on last argument](https://github.com/teppokoivula/VersionControl/blob/370bc2629181760014bfe2121d2bc567933a6a22/ProcessVersionControl.module#L630) causes a parse error:

![2020-01-29_120438](https://user-images.githubusercontent.com/1538852/73313356-ddf81100-428f-11ea-8fb4-4c203f372496.png)

**Comment by devsmo** [comment]
Looks like this bug has not been fixed.
I have the same error. It's fixed by removing the comma on line 665.

**Comment by teppokoivula** [comment]
Thanks for reporting this, should be fixed now in the dev branch.
