### ISSUE TITLE
Bug: Missing required GET param pages_id

### ISSUE THREAD

**Issue by q2apro** [teppokoivula/VersionControl#3]
Hi, I have tried your module but get: 

    {"error":true,"message":"Missing required GET param pages_id"}

output on top of the page after saving. 

I also wonder where to find the history of all page edits. 

In the readme, the information is missing how to access the page history and revert. Can you please add this. It would help others too.

**Comment by teppokoivula** [comment]
@q2apro: thanks for reporting this!

First of all, are you using PHP 7? I've just received a similar issue report, and in that case the error was only reproducible using version 7; with earlier versions of PHP everything seemed to work as expected.

Also, which version of ProcessWire are you using?

Regarding the documentation part, I'm going to add a note to revise this later. You're right in that it could be more obvious. I've posted more instructions to the support forum, but still :)

**Comment by q2apro** [comment]
1. PHP 7 on localhost
2. Latest version of PW (3.0.29)
3. Thanks for the docs.

**Comment by teppokoivula** [comment]
The issue with GET params should be fixed now. Please let me know if it persists.

**Comment by q2apro** [comment]
I cannot test it because I do not find the options anymore. Really need more "how-to"-info in the readme...
