### ISSUE TITLE
Permission denied (not editable) error appearing above admin masthead when non-superuser edits a user.

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#33]
@teppokoivula - I have other users with the `user-admin` permission, but when I have version control enabled for the user template (I have a biography textarea field here), then they get this error. It doesn't affect their ability to edit, but it's obviously in error still.

![image](https://user-images.githubusercontent.com/871211/109820459-da992c80-7be9-11eb-9189-fcf16729c173.png)

I am using the alternate user parent / template setup so maybe that is contributing to the problem?

Thanks.

**Comment by teppokoivula** [comment]
Thanks for reporting this, @adrianbj. Had a quick look, and the underlying reason for this is that PagePermissions provides access to user pages with user-admin permission only in case current Process matches one of the expected values, which obviously won't include ProcessVersionControl.

Not quite certain yet how to navigate around that, so will have to get back to this later :)

**Comment by teppokoivula** [comment]
Hey @adrianbj — this should now be fixed in version 2.4.4 (dev). I don't think the issue applies to 1.x branch, so I'm assuming you're using 2.x, but let me know if not :)

**Comment by adrianbj** [comment]
Thanks @teppokoivula
