### ISSUE TITLE
Restore Revision not working properly

### ISSUE THREAD

**Issue by jtrenaud1s** [teppokoivula/VersionControl#34]
Hi, I'm running on a fresh processwire install with a fresh install of the module. No third party/incompatible field types are being used. Tracked templates and fields have been configured properly upon module installation.;

Clicking the "Restore Revision" button on the history tab of a page for some revision will show the message that "Page restored to revision #X", however, the page content and the field values never get changed to the values in the revision that was supposed to be reverted to.

Edit: I can, however, revert an individual field to a selected revision. Reverting the entire page "acts" as if it worked, but none of the content is actually reverted changed.

**Comment by teppokoivula** [comment]
Hey @jtrenaud1s — thanks for reporting this. Which version of VersionControl do you have installed?

**Comment by jtrenaud1s** [comment]
1.3.1, with 1.3.0 for the interface module, thanks for the quick response!

**Comment by teppokoivula** [comment]
Sorry for the delay — this should now be fixed in the latest versions (1.3.3 master and 2.4.5 dev), though let me know if the issue persists.
