### ISSUE TITLE
PHP Warning: Undefined variable $object in .../VersionControl/VersionControl.module:354

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#35]
Hi @teppokoivula - seeing this in the latest version (committed yesterday) whenever I save a page. It looks like you just need to change all instances of `$object` with `$page`, but maybe I am missing something.

Let me know if you have any problems reproducing.

BTW, I am running PHP8 and everything else so far seems fixed with this new version.

**Comment by teppokoivula** [comment]
Thanks for the report, @adrianbj! This should be fixed in 2.4.6.
