### ISSUE TITLE
Argument must be of type Countable  when applied to field inside repeater

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#38]
Hi @teppokoivula - I fixed it quickly by replacing `count()` with `wireCount()`

![image](https://user-images.githubusercontent.com/871211/136115662-65b22f50-c3f4-4079-8308-a90c1727a442.png)

**Comment by teppokoivula** [comment]
This should now be fixed in both master and dev branches.

**Comment by adrianbj** [comment]
Thanks!
