### ISSUE TITLE
[DOM] Found 2 elements with non-unique id #Inputfield_id

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#43]
Hi @teppokoivula - I am seeing this error in the browser console when viewing a user page (Access > Users > xxxxxx). It seems to be coming from the History tab.

Obviously you'll need version control on for some of the fields on the user template. Please let me know if you have any problems reproducing.

Thanks.

**Comment by teppokoivula** [comment]
Thanks for reporting, @adrianbj, and sorry for the delay. This is now fixed in master and dev branches.

**Comment by adrianbj** [comment]
Thank you!
