### ISSUE TITLE
count(): Argument #1 ($value) must be of type Countable|array, null given

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#44]
Hi @teppokoivula - I get this when clicking the eye icon on the history tab. `wireCount()` does take care of it if you want to take that approach.

Thanks!

<img width="828" alt="image" src="https://user-images.githubusercontent.com/871211/179844107-5409dc95-5587-42cc-9a28-94ebb6b4631a.png">

**Comment by teppokoivula** [comment]
Hey @adrianbj — it looks like this was already fixed in https://github.com/teppokoivula/VersionControl/commit/7ba687c731d1006b9e9d18e5f2a05e8ab6cad880. Can you check that you're using the latest version?

**Comment by adrianbj** [comment]
Ah, yes. Sorry, I am running v2 so I don't get notifications of updates via the PW Upgrades module.
