### ISSUE TITLE
PHP Notice: Trying to get property of non-object in .../VersionControl/ProcessVersionControl.module:654

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/VersionControl#6]
This happens when you have RepeaterMatrix fields (I don't think it affects normal Repeater fields) on the page.

The fields end up being named things like: `body_repeater2143` 

Maybe not the best fix, but as I quick test, I confirmed that if you add this line before Line 654, it fixes it:

```
$field = preg_replace('/\d/', '', str_replace('_repeater','', $field));
```

**Comment by teppokoivula** [comment]
@adrianbj: sorry for taking so long to answer!

I've been trying to reproduce this issue, but so far no luck. It could be that something has changed, or perhaps I should say fixed, in the meantime – but just to make sure, you wouldn't happen to still have a test case available for this? :)

On a slightly related note, Repeaters don't seem to work too well with this module. I'm pretty sure they never did, so it's probably nothing new, more likely something to be added to the backlog.

**Comment by teppokoivula** [comment]
No luck at reproducing this one, so I'm closing the issue.
